### ISSUE TITLE
Table Names

### ISSUE THREAD

**Issue by rdclag** [miltador/AspNetCore.Identity.DynamoDB#6]
DynamoDB tables for users and roles are created using the names in appsettings.json.  However, the dll is using set values (constants) for the table names: [DynamoDBTable("users")], [DynamoDBTable("roles")].

**Comment by miltador** [comment]
These are default values for table name.
You can easily override them during initialization, as shown here: https://github.com/miltador/AspNetCore.Identity.DynamoDB/blob/master/samples/IdentitySample.Mvc/Startup.cs#L170

**Comment by rdclag** [comment]
The line of code that you highlighted creates a table in the DynamoDB using the name specified in the app settings.  Having that setting is very handy so that each application has its own user table in DynamoDB - "app1users", "app2users", etc.  The high-level read and write operations that you have in your code are not using the table names from the app setting.  They are using preset constants - "users" and those constants are not overridden by the app settings.  I suggest using the lower-level DynamoDB API for read/write operations where the table name is entered as a variable.

**Comment by miltador** [comment]
It is overriden by setting [aliases](https://github.com/miltador/AspNetCore.Identity.DynamoDB/blob/master/src/AspNetCore.Identity.DynamoDB/DynamoUserStore.cs#L777) so it maps e.g. `users` to the appsettings table name.

**Comment by rdclag** [comment]
That line of code looks like it should override the constant. It doesn't work for me. Thanks.
